### ISSUE TITLE
Kafka coredump created for topic list command on Kafka broker

### ISSUE THREAD

**Issue by raz08** [banzaicloud/koperator#1074]
## Description

Tried to list kafka topics from the Kafka broker by exec into one of the broker pod. Got error with address bind exception and created coredump. 

_$kubectl exec -ti kafka-0-wmdcv -n kafka -- sh
#/opt/kafka/bin/kafka-topics.sh --bootstrap-server=kafka-headless.kafka.svc.cluster.local:29092 --list_

`

Exception in thread "main" java.lang.reflect.InvocationTargetException
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
        at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
        at java.base/java.lang.reflect.Method.invoke(Unknown Source)
        at java.instrument/sun.instrument.InstrumentationImpl.loadClassAndStartAgent(Unknown Source)
        at java.instrument/sun.instrument.InstrumentationImpl.loadClassAndCallPremain(Unknown Source)
Caused by: java.net.BindException: Address already in use
        at java.base/sun.nio.ch.Net.bind0(Native Method)
        at java.base/sun.nio.ch.Net.bind(Unknown Source)
        at java.base/sun.nio.ch.ServerSocketChannelImpl.netBind(Unknown Source)
        at java.base/sun.nio.ch.ServerSocketChannelImpl.bind(Unknown Source)
        at java.base/sun.nio.ch.ServerSocketAdaptor.bind(Unknown Source)
        at jdk.httpserver/sun.net.httpserver.ServerImpl.<init>(Unknown Source)
        at jdk.httpserver/sun.net.httpserver.HttpServerImpl.<init>(Unknown Source)
        at jdk.httpserver/sun.net.httpserver.DefaultHttpServerProvider.createHttpServer(Unknown Source)
        at jdk.httpserver/com.sun.net.httpserver.HttpServer.create(Unknown Source)
        at io.prometheus.jmx.shaded.io.prometheus.client.exporter.HTTPServer.<init>(HTTPServer.java:176)
        at io.prometheus.jmx.shaded.io.prometheus.jmx.JavaAgent.premain(JavaAgent.java:31)
        ... 6 more
*** java.lang.instrument ASSERTION FAILED ***: "result" with message agent load/premain call failed at ../src/java.instrument/share/native/libinstrument/JPLISAgent.c line: 422
FATAL ERROR in native method: processing of -javaagent failed, processJavaStart failed
Aborted (core dumped)
`
## Expected Behavior

For any wrong command given by user there should not be any coredumps or crash

## Actual Behavior

Coredump created for wrong or unknown command or addressbind exception

## Affected Version

Please provide the version number where this issue was encountered.

## Steps to Reproduce

1. First step
1. Second step
1. etc.

## Checklist

- [ ] I have read the [contributing guidelines](../CONTRIBUTING.md)
- [ ] I have verified this does not duplicate an existing issue

**Comment by bartam1** [comment]
Hello!
You need to unset the KAFKA_OPTS env variable first.
Please try this:  #unset KAFKA_OPTS
