### ISSUE TITLE
[docs] Sample Kafka Clusters setting auto.create.topics.enable=true by default 

### ISSUE THREAD

**Issue by cbuto** [banzaicloud/koperator#720]
Hello! first of all, thanks for maintaining this project!

While going through some of the samples in the `config/samples` directory, I noticed that cruise control will not start unless certain topics exist in the Kafka cluster. 

I'm wondering if the samples should set `auto.create.topics.enable=true` by default. If not, would some documentation be sufficient to help to diagnose the issue. It could either be guidance on how to create the topic manually or how to set `auto.create.topics.enable=true` in the sample resources (maybe both?)

Here’s a snippet of the exception that cruise control throws if the topic it expects doesn’t exist:

```
Exception in thread "main" java.lang.IllegalStateException: Cruise Control cannot find sampling topic matches __CruiseControlMetrics in the target cluster.
```

Thanks!

**Comment by stoader** [comment]
If `cruise.control.metrics.topic.auto.create=true` than CC creates the topic it needs. This doesn't require `auto.create.topics.enable=true` in fact for prod environment it's recommended to have `auto.create.topics.enable=have` and provide the right ACLs for each client application that needs to create topics.

See https://github.com/banzaicloud/koperator/blob/master/config/samples/banzaicloud_v1beta1_kafkacluster.yaml#L69

**Comment by cbuto** [comment]
@stoader ah makes sense. I guess the exception I saw ended up being a symptom of SSL issues when using this [sample](https://raw.githubusercontent.com/banzaicloud/koperator/master/config/samples/simplekafkacluster_ssl.yaml). Not quite sure why but I can close this issue for now. thanks!

```
[2021-12-13 15:21:53,906] ERROR [AdminClient clientId=CruiseControlMetricsReporter] Connection to node -1 (localhost/127.0.0.1:29092) failed authentication due to: SSL handshake failed (org.apache.kafka.clients.NetworkClient)
[2021-12-13 15:21:53,906] WARN [AdminClient clientId=CruiseControlMetricsReporter] Metadata update failed due to authentication error (org.apache.kafka.clients.admin.internals.AdminMetadataManager)
org.apache.kafka.common.errors.SslAuthenticationException: SSL handshake failed
Caused by: javax.net.ssl.SSLHandshakeException: No subject alternative DNS name matching localhost found.
    at java.base/sun.security.ssl.Alert.createSSLException(Unknown Source)
    at java.base/sun.security.ssl.TransportContext.fatal(Unknown Source)
    at java.base/sun.security.ssl.TransportContext.fatal(Unknown Source)
    at java.base/sun.security.ssl.TransportContext.fatal(Unknown Source)
    at java.base/sun.security.ssl.CertificateMessage$T13CertificateConsumer.checkServerCerts(Unknown Source)
    at java.base/sun.security.ssl.CertificateMessage$T13CertificateConsumer.onConsumeCertificate(Unknown Source)
    at java.base/sun.security.ssl.CertificateMessage$T13CertificateConsumer.consume(Unknown Source)
    at java.base/sun.security.ssl.SSLHandshake.consume(Unknown Source)
    at java.base/sun.security.ssl.HandshakeContext.dispatch(Unknown Source)
    at java.base/sun.security.ssl.SSLEngineImpl$DelegatedTask$DelegatedAction.run(Unknown Source)
    at java.base/sun.security.ssl.SSLEngineImpl$DelegatedTask$DelegatedAction.run(Unknown Source)
    at java.base/java.security.AccessController.doPrivileged(Native Method)
    at java.base/sun.security.ssl.SSLEngineImpl$DelegatedTask.run(Unknown Source)
    at org.apache.kafka.common.network.SslTransportLayer.runDelegatedTasks(SslTransportLayer.java:430)
    at org.apache.kafka.common.network.SslTransportLayer.handshakeUnwrap(SslTransportLayer.java:514)
    at org.apache.kafka.common.network.SslTransportLayer.doHandshake(SslTransportLayer.java:368)
    at org.apache.kafka.common.network.SslTransportLayer.handshake(SslTransportLayer.java:291)
    at org.apache.kafka.common.network.KafkaChannel.prepare(KafkaChannel.java:173)
    at org.apache.kafka.common.network.Selector.pollSelectionKeys(Selector.java:547)
    at org.apache.kafka.common.network.Selector.poll(Selector.java:485)
    at org.apache.kafka.clients.NetworkClient.poll(NetworkClient.java:544)
    at org.apache.kafka.clients.admin.KafkaAdminClient$AdminClientRunnable.processRequests(KafkaAdminClient.java:1293)
    at org.apache.kafka.clients.admin.KafkaAdminClient$AdminClientRunnable.run(KafkaAdminClient.java:1224)
    at java.base/java.lang.Thread.run(Unknown Source)
Caused by: java.security.cert.CertificateException: No subject alternative DNS name matching localhost found.
    at java.base/sun.security.util.HostnameChecker.matchDNS(Unknown Source)
    at java.base/sun.security.util.HostnameChecker.match(Unknown Source)
    at java.base/sun.security.ssl.X509TrustManagerImpl.checkIdentity(Unknown Source)
    at java.base/sun.security.ssl.X509TrustManagerImpl.checkIdentity(Unknown Source)
    at java.base/sun.security.ssl.X509TrustManagerImpl.checkTrusted(Unknown Source)
    at java.base/sun.security.ssl.X509TrustManagerImpl.checkServerTrusted(Unknown Source)
    ... 20 more
[2021-12-13 15:21:53,906] INFO [SocketServer brokerId=2] Failed authentication with /127.0.0.1 (SSL handshake failed) (org.apache.kafka.common.network.Selector)
```
