### ISSUE TITLE
Unable to run kafka pod with sasl_plaintext for internalListeners

### ISSUE THREAD

**Issue by yaoyao12138** [banzaicloud/koperator#722]
**Describe the bug**
kafka pod restart again and again with sasl_plaintext for internalListeners.

**Steps to reproduce the issue:**
Follow the quickstart https://banzaicloud.com/docs/supertubes/kafka-operator/install-kafka-operator/ and change the https://github.com/banzaicloud/koperator/blob/master/config/samples/simplekafkacluster.yaml#L55 `plaintext` to `sasl_plaintext`, kafka pod restart again and again with sasl_plaintext for internalListeners.

```
root@vm-64-publicvlan-vm-env:~# kubectl get pods -A
NAMESPACE      NAME                                                   READY   STATUS      RESTARTS   AGE
kube-system    coredns-7448499f4d-rgfcc                               1/1     Running     0          48m
kube-system    metrics-server-86cbb8457f-579vp                        1/1     Running     0          48m
kube-system    local-path-provisioner-5ff76fc89d-n9ws4                1/1     Running     0          48m
default        ambassador-agent-69bdc547bd-j9fwq                      1/1     Running     0          48m
default        svclb-ambassador-gqks9                                 2/2     Running     0          48m
default        nfs-subdir-external-provisioner-58d7d94999-x9589       1/1     Running     0          47m
default        ambassador-6677db9456-qr2h7                            1/1     Running     0          48m
default        ambassador-6677db9456-2w856                            1/1     Running     0          48m
default        ambassador-6677db9456-ccgrn                            1/1     Running     0          48m
cert-manager   cert-manager-cainjector-54f4cc6b5-wkxtj                1/1     Running     0          43m
cert-manager   cert-manager-848f547974-rqqfx                          1/1     Running     0          43m
cert-manager   cert-manager-webhook-7c9588c76-wrmpp                   1/1     Running     0          43m
zookeeper      zookeeper-operator-697b777786-zj75g                    1/1     Running     0          41m
zookeeper      zookeeper-0                                            1/1     Running     0          40m
default        prometheus-kube-prometheus-operator-85757cb64f-jx78r   1/1     Running     0          33m
kafka          kafka-operator-operator-57bf4949c9-c7l58               2/2     Running     0          31m
kafka          kafka-0-85jh9                                          0/1     Completed   0          11s
```
```
root@vm-64-publicvlan-vm-env:~# kc logs kafka-0-85jh9 -n kafka
...
[2021-12-14 09:31:19,894] ERROR [KafkaServer id=0] Fatal error during KafkaServer startup. Prepare to shutdown (kafka.server.KafkaServer)
java.lang.IllegalArgumentException: Could not find a 'KafkaServer' or 'internal.KafkaServer' entry in the JAAS configuration. System property 'java.security.auth.login.config' is not set
	at org.apache.kafka.common.security.JaasContext.defaultContext(JaasContext.java:131)
	at org.apache.kafka.common.security.JaasContext.load(JaasContext.java:96)
	at org.apache.kafka.common.security.JaasContext.loadServerContext(JaasContext.java:69)
	at org.apache.kafka.common.network.ChannelBuilders.create(ChannelBuilders.java:143)
	at org.apache.kafka.common.network.ChannelBuilders.serverChannelBuilder(ChannelBuilders.java:107)
	at kafka.network.Processor.<init>(SocketServer.scala:853)
	at kafka.network.SocketServer.newProcessor(SocketServer.scala:442)
	at kafka.network.SocketServer.$anonfun$addDataPlaneProcessors$1(SocketServer.scala:299)
	at scala.collection.immutable.Range.foreach$mVc$sp(Range.scala:190)
	at kafka.network.SocketServer.addDataPlaneProcessors(SocketServer.scala:297)
	at kafka.network.SocketServer.$anonfun$createDataPlaneAcceptorsAndProcessors$1(SocketServer.scala:262)
	at kafka.network.SocketServer.$anonfun$createDataPlaneAcceptorsAndProcessors$1$adapted(SocketServer.scala:259)
	at scala.collection.IterableOnceOps.foreach(IterableOnce.scala:563)
	at scala.collection.IterableOnceOps.foreach$(IterableOnce.scala:561)
	at scala.collection.AbstractIterable.foreach(Iterable.scala:919)
	at kafka.network.SocketServer.createDataPlaneAcceptorsAndProcessors(SocketServer.scala:259)
	at kafka.network.SocketServer.startup(SocketServer.scala:131)
	at kafka.server.KafkaServer.startup(KafkaServer.scala:285)
	at kafka.Kafka$.main(Kafka.scala:109)
	at kafka.Kafka.main(Kafka.scala)
[2021-12-14 09:31:19,896] INFO [KafkaServer id=0] shutting down (kafka.server.KafkaServer)
[2021-12-14 09:31:19,898] INFO [SocketServer listenerType=ZK_BROKER, nodeId=0] Stopping socket server request processors (kafka.network.SocketServer)
[2021-12-14 09:31:19,901] INFO [SocketServer listenerType=ZK_BROKER, nodeId=0] Stopped socket server request processors (kafka.network.SocketServer)
[2021-12-14 09:31:19,906] INFO Shutting down. (kafka.log.LogManager)
...
```
And add `listener.name.sasl_ssl.plain.sasl.jaas.config=org.apache.kafka.common.security.plain.PlainLoginModule required username="admin" password="admin-secret" user_admin="admin-secret" user_alice="alice-secret"`to the configmap of this pod which follows the jaas config way, https://docs.confluent.io/platform/current/kafka/authentication_sasl/authentication_sasl_plain.html#, but the configmap seems couldn't be added anything manually.
So how could I use username/password like https://github.com/Shopify/sarama/blob/v1.30.0/config.go#L82-L84 in kafka API? Where could I set like secret in koperator?

**Comment by panyuenlau** [comment]
Hey @yaoyao12138, see the following configuration snippet for `KafkaClsuter`:
```yaml
apiVersion: kafka.banzaicloud.io/v1beta1
kind: KafkaCluster
metadata:
  labels:
    controller-tools.k8s.io: "1.0"
  name: kafka
spec:
  headlessServiceEnabled: true
  zkAddresses:
    - "zookeeper-client.zookeeper:2181"
  propagateLabels: false
  oneBrokerPerNode: false
  clusterImage: "ghcr.io/banzaicloud/kafka:2.13-3.1.0"
  readOnlyConfig: |
    auto.create.topics.enable=false
    cruise.control.metrics.topic.auto.create=true
    cruise.control.metrics.topic.num.partitions=1
    cruise.control.metrics.topic.replication.factor=2
    # configure kafka brokers to use SASL/PLAIN authentication mechanism
    sasl.enabled.mechanisms=PLAIN
    # specify the JAAS configure to the corresponding internal listener that with name "sasl_int" in the listenersConfig section
    listener.name.sasl_int.plain.sasl.jaas.config=org.apache.kafka.common.security.plain.PlainLoginModule required \
      username="admin" \
      password="admin-secret" \
      user_admin="admin-secret";
  listenersConfig:
    internalListeners:
      - type: "plaintext"
        name: "internal"
        containerPort: 29092
        usedForInnerBrokerCommunication: true
      - type: "plaintext"
        name: "controller"
        containerPort: 29093
        usedForInnerBrokerCommunication: false
        usedForControllerCommunication: true
      - type: "sasl_plaintext"
        name: "sasl_int"
        containerPort: 29094
        usedForInnerBrokerCommunication: false
...
```

Then after the koperator brings up all the broker pods, you can perform the following steps to test the internal listener configurations for the kafka brokers:
1. Create a Kafka topic
```
kubectl apply -n kafka -f -<<EOF
apiVersion: kafka.banzaicloud.io/v1alpha1
kind: KafkaTopic
metadata:
    name: kafkacat-topic
spec:
    clusterRef:
        name: kafka
    name: kafkacat-topic
    partitions: 1
    replicationFactor: 1
    config:
        "retention.ms": "604800000"
        "cleanup.policy": "delete"
EOF
```

2. Create a pod with kcat for testing
```
kubectl apply -n kafka -f- <<EOF
apiVersion: v1
kind: Pod
metadata:
  name: kcat
spec:
  containers:
  - name: kafka-test
    image: "edenhill/kcat:1.7.0"
    # Just spin & wait forever
    command: [ "/bin/sh", "-c", "--" ]
    args: [ "while true; do sleep 3000; done;" ]
EOF
```

3. Exec into the testing pod and run the following kcat command:
```
kcat -L -b kafka-headless:29094 -t kafkacat-topic -X security.protocol=SASL_PLAINTEXT -X sasl.mechanisms=PLAIN -X sasl.username=admin -X sasl.password=admin-secret
```
Example response you will be getting:
```
Metadata for kafkacat-topic (from broker -1: sasl_plaintext://kafka-headless:29094/bootstrap):
 3 brokers:
  broker 0 at kafka-0.kafka-headless.kafka.svc.cluster.local:29094
  broker 2 at kafka-2.kafka-headless.kafka.svc.cluster.local:29094 (controller)
  broker 1 at kafka-1.kafka-headless.kafka.svc.cluster.local:29094
 1 topics:
  topic "kafkacat-topic" with 1 partitions:
    partition 0, leader 2, replicas: 2, isrs: 2
```

**Comment by panyuenlau** [comment]
Note that the configurations of each broker are stored as `configmap` in the k8s cluster, with the `readOnlyConfig` and `listenersConfig` specified in the above `KafkaCluster` CR, the following configmap is generated for `kafka0` by the koperator:
```
k get configmap kafka-config-0 -n kafka -o yaml
apiVersion: v1
data:
  broker-config: |
    advertised.listeners=CONTROLLER://kafka-0.kafka-headless.kafka.svc.cluster.local:29093,INTERNAL://kafka-0.kafka-headless.kafka.svc.cluster.local:29092,SASL_INT://kafka-0.kafka-headless.kafka.svc.cluster.local:29094
    auto.create.topics.enable=false
    broker.id=0
    control.plane.listener.name=CONTROLLER
    cruise.control.metrics.reporter.bootstrap.servers=kafka-headless.kafka.svc.cluster.local:29092
    cruise.control.metrics.reporter.kubernetes.mode=true
    cruise.control.metrics.topic.auto.create=true
    cruise.control.metrics.topic.num.partitions=1
    cruise.control.metrics.topic.replication.factor=2
    inter.broker.listener.name=INTERNAL
    listener.name.sasl_int.plain.sasl.jaas.config=org.apache.kafka.common.security.plain.PlainLoginModule required username="admin" password="admin-secret" user_admin="admin-secret";
    listener.security.protocol.map=INTERNAL:PLAINTEXT,CONTROLLER:PLAINTEXT,SASL_INT:SASL_PLAINTEXT
    listeners=INTERNAL://:29092,CONTROLLER://:29093,SASL_INT://:29094
    log.dirs=/kafka-logs/kafka
    metric.reporters=com.linkedin.kafka.cruisecontrol.metricsreporter.CruiseControlMetricsReporter
    sasl.enabled.mechanisms=PLAIN
    zookeeper.connect=zookeeper-client.zookeeper:2181/
kind: ConfigMap
metadata:
  annotations:
    banzaicloud.com/last-applied: UEsDBBQACAAIAAAAAAAAAAAAAAAAAAAAAAAIAAAAb3JpZ2luYWycVE1v4zYQ/SsBzxITO0nbqNAhSPcQ1JssvEFRoCqCETl2WFFDdYbKorvwfy+orzgtiu3mYpOPb0bDN/P4RVmIoIovqubQIOcm0M7tVaHAPiNHJ2i1dxKRkKW8ub972N5vNu+2xelpA7sG8jM9/j8hWI8i41bLs9HG9xKRtQ8GfLG+Ors6z27vHt5t7643b4tfZx+vP24eb+8e3hZ/URH0MWjDCBF1DJ0zopGg9ljuwAtWNAqhnS3PKjKBIgevOw+EixCaoMUjMSoy3DtBPdNbjJwyM3aBUwl1CFEiQ6cF+TlJ+Q1Vr7+ev+lrZMKIottgsYzc439GDdfWR0L8Hzr1re6Ao4sukJSrr9AZO+8MJLLegYmBy3VFjgYxRoVfqzkPRkWvcC0g/tFRTC1wNGz1HwCix0ktA+81dGCecNLQhLYNpAVNzy7+NcV9SL+bsHf0Ptje4wnjn71jtCe9IA8VVAps66hSJx2IfApsZygXNIyxUgP5ccD+dfbjUeUvH+cQg0nqQLdcsfiwuU7rXx+yI0O9gMuMD4sFf8kv5ZGNJmO8suZktiOzzOPvw15bx1JO9vFhL+OyorGDy1BJaUKrvaMGraNZ3aHp/+j5MoY3w+nNePp+PNxOhxUNvRvNZnWL5gnISSvlcMOKPofQIHbIqbWEJpYLkhvvkKJegGK9+mF1WpE6ZKrFCPMr5qFGL2kFXacKNRStsul1u7WqUGcqG+FHwwvjkKk0A/N+egbzxE24dGDwKF34RMhb3CEjGRRV/JY+6H5BFhdoJuoa6DM440NvtQunz6saI6xSOT6Y5j4l+Qk9xiEmeTBTk7IeeUYaR6nsn1PGm/FtUK+rVZnqXeJY3MHu4nKdw2p3nl98t7rM67W1eX11ebFaG/s91Ofq8Pvh8HcAAAD//1BLBwhr9q95qwIAAPcFAABQSwECFAAUAAgACAAAAAAAa/aveasCAAD3BQAACAAAAAAAAAAAAAAAAAAAAAAAb3JpZ2luYWxQSwUGAAAAAAEAAQA2AAAA4QIAAAAA
  creationTimestamp: "2022-08-01T07:38:27Z"
  labels:
    app: kafka
    brokerId: "0"
    kafka_cr: kafka
  name: kafka-config-0
  namespace: kafka
  ownerReferences:
  - apiVersion: kafka.banzaicloud.io/v1beta1
    blockOwnerDeletion: true
    controller: true
    kind: KafkaCluster
    name: kafka
    uid: defaf452-a1f3-4615-b2dd-b95412cd7ab3
  resourceVersion: "9177334"
  uid: 28515742-12b1-4931-99c2-056993ab1fa3
```

**Comment by panyuenlau** [comment]
Closing the issue since requested information has been provided to the reporter
